# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=50)),
                ('SurName', models.CharField(max_length=50)),
                ('UniversityStage', models.CharField(max_length=45)),
                ('Gender', models.CharField(max_length=45)),
                ('Address', models.CharField(max_length=50)),
                ('BirthDate', models.DateField()),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
