# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20160228_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
