# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
