# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_delete_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstCourse', models.IntegerField()),
                ('SecondCourse', models.IntegerField()),
                ('Average', models.IntegerField()),
                ('FinalExam', models.IntegerField()),
                ('Result', models.CharField(max_length=20)),
            ],
        ),
    ]
