# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Marks',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.Marks'),
            preserve_default=False,
        ),
    ]
