# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_student_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='object',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
