# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20160305_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.Department'),
            preserve_default=False,
        ),
    ]
