# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20160305_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResearchTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specilization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=50)),
                ('SurName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.ScientificResearch')),
                ('Specilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Specilization')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseDate',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='teacher_course',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Course'),
        ),
        migrations.AddField(
            model_name='teacher_course',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Teacher'),
        ),
    ]
