# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20160305_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Research',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='college.ScientificResearch'),
        ),
    ]
