# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_auto_20160309_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Marks_ID',
        ),
        migrations.AddField(
            model_name='student',
            name='Subject_ID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='college.Subject'),
            preserve_default=False,
        ),
    ]
