# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_auto_20160309_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='Student',
            new_name='Student_ID',
        ),
    ]
